/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'paulsmout' at '12/09/16 20:53' with Gradle 2.14.1
 *
 * @author paulsmout, @date 12/09/16 20:53
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
