/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'paulsmout' at '12/09/16 20:53' with Gradle 2.14.1
 *
 * @author paulsmout, @date 12/09/16 20:53
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
